# Generated by Django 3.0.8 on 2020-10-18 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_of_residence', models.CharField(max_length=40)),
                ('country_of_residence', models.CharField(max_length=40)),
                ('Image', models.ImageField(upload_to='home/user_images')),
                ('bio', models.TextField()),
                ('user_inher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
