# Generated by Django 3.1.5 on 2021-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Image',
            field=models.ImageField(default='media/asset/images/1_TrnL6Aj.PNG', upload_to='home/user_images'),
        ),
    ]
