# Generated by Django 3.1.1 on 2021-03-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210127_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='not@provided.com', max_length=150),
        ),
    ]
