# Generated by Django 3.1.1 on 2021-03-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Image',
            field=models.ImageField(default='media/asset/images/1_TrnL6Aj.png', upload_to='home/user_images'),
        ),
    ]
