# Generated by Django 3.1.1 on 2021-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210314_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Image_background',
            field=models.ImageField(default='media/asset/images/user_default.png', upload_to='home/user_images'),
        ),
    ]
