# Generated by Django 3.1.5 on 2021-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210310_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chat_room_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
