# Generated by Django 3.1.1 on 2021-03-10 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210310_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user_id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
