# Generated by Django 3.1.1 on 2021-03-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210310_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user_id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
