# Generated by Django 3.1.1 on 2021-03-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210310_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='user_id',
            new_name='user_fk',
        ),
    ]
