# Generated by Django 3.1.5 on 2021-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=100)),
                ('receiver_username', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('request_status', models.BooleanField(default=False)),
            ],
        ),
    ]
