# Generated by Django 3.1.5 on 2021-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='date_received',
            field=models.DateField(auto_now=True),
        ),
    ]
