# Generated by Django 3.1.1 on 2021-03-29 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_secret_key',
            name='date_valid',
            field=models.DateTimeField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
