# Generated by Django 3.1.1 on 2021-02-28 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210227_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
