# Generated by Django 3.1.1 on 2021-03-30 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210329_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_secret_key',
            name='date_valid',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 6, 42, 58, 398602)),
        ),
    ]
