# Generated by Django 3.1.1 on 2021-04-04 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210330_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_secret_key',
            name='date_valid',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 16, 8, 24, 703622)),
        ),
    ]
