# Generated by Django 3.0.8 on 2020-12-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201208_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
